### ISSUE TITLE
Past Shows display has many gaps, omitting shows listed under All Shows

### ISSUE THREAD

**Issue by kaweir** [sweir27/coop_gallery_213#23]
![image](https://cloud.githubusercontent.com/assets/6365118/21897770/8fc94d1c-d8b8-11e6-9037-a32e8abe68b1.png)

![image](https://cloud.githubusercontent.com/assets/6365118/21897716/7041b24a-d8b8-11e6-8b4c-c4b4199bca7d.png)

**Comment by sweir27** [comment]
I think this is fixed now on the user-facing view.
